sonar.projectKey=NikolasTrapp_sticker-swap-frontend
sonar.organization=nikolastrapp

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/sticker-swap-frontend/lcov.info
sonar.qualitygate.wait=true
